# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openhook < Formula
  desc "Event routing and channels for AI agents"
  homepage "https://openhook.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.0/openhook_0.3.0_darwin_amd64.tar.gz"
      sha256 "0c41b2715582afe18983e8f2ed6fd37b9a9fb919b36e01d770aa8017b954acba"

      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.0/openhook_0.3.0_darwin_arm64.tar.gz"
      sha256 "f619d53d671cdcc1a1b7690c7f6c970bf9b2b35f464a172c5c40a7c63ead925f"

      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.0/openhook_0.3.0_linux_amd64.tar.gz"
      sha256 "199fb80c669afd596e747471dc4bebfd1f683465a858d02f3d107b64d41d0629"
      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.0/openhook_0.3.0_linux_arm64.tar.gz"
      sha256 "0ca9827a911cf0001e5a6a6476bc0b62af49e27b959cc9a3256f9694c53ed4da"
      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  test do
    system "#{bin}/openhook", "--help"
  end
end
