# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openhook < Formula
  desc "Webhook relay service for AI agents - receive events from GitHub, Stripe, Linear"
  homepage "https://openhook.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openhook-dev/openhook/releases/download/v0.1.0/openhook_0.1.0_darwin_amd64.tar.gz"
      sha256 "315ca647ce731bd4cec9781ca5afaf3be45e343a4a468a2074172c8ebee2aeb9"

      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openhook-dev/openhook/releases/download/v0.1.0/openhook_0.1.0_darwin_arm64.tar.gz"
      sha256 "ac11f9a57636f4d0c1bd5ef5cc1d657bd6619f617a3441146e97b6381eb3260b"

      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook/releases/download/v0.1.0/openhook_0.1.0_linux_amd64.tar.gz"
      sha256 "1ae6ab1bf6f3b509ce26bc336d709cd190929dcafa2655c31bb91257c28e21df"
      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook/releases/download/v0.1.0/openhook_0.1.0_linux_arm64.tar.gz"
      sha256 "017016d68dfe609d1f6af5663931caffe26b6ddbd03b70394e4824a607204352"
      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  test do
    system "#{bin}/openhook", "--help"
  end
end
