# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openhook < Formula
  desc "Event routing and channels for AI agents"
  homepage "https://openhook.dev"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.1/openhook_0.3.1_darwin_amd64.tar.gz"
      sha256 "063d6c3b3db1cbec7068dcb0e9ac46653c2a9b1af7aaacb401c05f29d279b658"

      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.1/openhook_0.3.1_darwin_arm64.tar.gz"
      sha256 "af7c50ea5a2a76fc5a217bd6b1e7ff15b58ec0aa769438d3b9bd635fb21e3b24"

      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.1/openhook_0.3.1_linux_amd64.tar.gz"
      sha256 "0181c7d1325fb1aa67553a3d2551825571db600ee4ec6e103331f6b2ca5c7c6b"
      define_method(:install) do
        bin.install "openhook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhook-dev/openhook-cli/releases/download/v0.3.1/openhook_0.3.1_linux_arm64.tar.gz"
      sha256 "6ade40ae4882647e37f09508674516aefc56d527d1eeb45517fe2b9c95f4afa3"
      define_method(:install) do
        bin.install "openhook"
      end
    end
  end

  test do
    system "#{bin}/openhook", "--help"
  end
end
